### ISSUE TITLE
enter_serial should come from the library user

### ISSUE THREAD

**Issue by emersion** [Smithay/smithay-clipboard#1]
You can't get an `enter_serial` if you just have a `wl_display`.

**Comment by trimental** [comment]
Its been decided that smithay-clipboard will internally keep track of all created seats and store the `enter_serial`s and connected `wl_data_device`s in a hash map with the seat name being the key. 

`store()` and `load()` will take a `seat_name` argument and use that to lookup the hash map.

**Comment by emersion** [comment]
Oh, right. I think it's fine, because enter serials will be broadcast to all `wl_keyboard` objects for the seat.
