### ISSUE TITLE
Deadlocking

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay-clipboard#3]
It seems like there are some deadlocking issues with the library which might be caused by reading from/writing into the same application.

More info here:
https://github.com/jwilm/alacritty/pull/2207

**Comment by trimental** [comment]
Hopefully this is fixed by https://github.com/Smithay/smithay-clipboard/commit/d2e552405b5e1e3b7c604c5b9bb916fcbf1337df

**Comment by chrisduerr** [comment]
I'm not able to reproduce with the latest master!
