### ISSUE TITLE
Clipboard updates only once

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay-clipboard#33]
This was reported to Alacritty in https://github.com/alacritty/alacritty/issues/4735.

It seems like the clipboard has an issue where it only updates its content once on some compositors (GNOME/weston) and requires users to switch applications before they can write to the clipboard again.

@r-c-f has provided a very helpful Wayland log, which suggests the problem might be with smithay-clipboard not cancelling the data source for the clipboard data: https://github.com/alacritty/alacritty/issues/4735#issuecomment-769735431

According to @jamesodhunt this regression was introduced in https://github.com/Smithay/smithay-clipboard/commit/f6f5b98235b1a5052aff1fb5a48e7951720beb42: https://github.com/alacritty/alacritty/issues/4735#issuecomment-769737024

**Comment by elinorbgr** [comment]
The cancelling is done by the server, not the client, so that is not the problem.

From the log, it appears to be an error in how smithay-clipboard handles its serials. Every `set_selection` call here is re-using the same serial, which causes the server to ignore all calls but the last. Looks like there is an issue in the serial-tracking logic.

**Comment by chrisduerr** [comment]
It seems like this is the serial handling logic:

https://github.com/Smithay/smithay-clipboard/blob/f6f5b98235b1a5052aff1fb5a48e7951720beb42/src/worker/mod.rs#L219-L228

It appears that it just takes the serial that was last observed and passes that to the function. While I do not know what exactly serials are, I'd assume this is an ever increasing ID. If this should be increased by the person submitting the `set_selection` call, I'd assume this might just be missing a `+= 1`?

**Comment by elinorbgr** [comment]
No, serial are ever-increasing numbers provided by the server at every input event (key press/release, mouse click, etc...), and whenever the client attempts to do something related to focus (accessing the clipboard for example), it needs to provide the serial of the input event justifying said action. If the serial provided by the client is outdated, the server will ignore the request, which is what happens here.

This mechanism serves for example to handle races between the client requesting access to the clipboard and focus changes: the server can allow clipboard access to a client for a short time *after* it has lost focus, as long as no other client has reacted to a more recent serial.

smithay-clipboard is supposed to bind the pointers and keyboard to keep track of the serials as they are sent by the server, but it seems something is wrong in this logic as the serial does not get updated.
