### ISSUE TITLE
Significant power usage in applications using this crate

### ISSUE THREAD

**Issue by nagisa** [Smithay/smithay-clipboard#34]
The implementation of this crate relies on a sleep loop to operate. However, that means it will also cause the CPU to wake up frequently even if there are no clipboard traffic of any kind in the system.

**Comment by elinorbgr** [comment]
Indeed.

This crate is, at its core, a workaround for the fact that winit has decided to *not* handle clipboard manipulations itself. If it had, a much more efficient implementation would have been possible.

The state of the crate can probably be improved, but it'll remain suboptimal unless winit changes its position (at which point this crate would no longer have any reason of existing).

**Comment by elinorbgr** [comment]
To provide more context, the correct thing to de in smithay-clipboard would be to monitor the Wayland socket using epoll to only be woken up when necessary, however as winit already does that itself, this has proven to be unreliable (only one of the sleeping threads is woken up when new data arrives, we need both).

If someone knows of a way to improve things,that would be welcome.

**Comment by zsugabubus** [comment]
If really there is no other way, could sleep duration be longer maybe?
