### ISSUE TITLE
Clipboard beyond small strings

### ISSUE THREAD

**Issue by WhyNotHugo** [Smithay/smithay-clipboard#43]
I'm [wanting to implement full clipboard support for iced](https://github.com/iced-rs/iced/discussions/1455), which uses [window_clipboard](https://github.com/hecrj/window_clipboard), which in turn uses this library under the hood.

The current API of `smithay-clipboard` is focused on handling small strings, and anything beyond that is not possible. Before any change can be made to the dependant libraries, it needs to happen here.

This would require some API changes, essentially extending the API here to better mirror the API of a clipboard (I say extend because I think the existing API can remain unchanged for backwards-compat).

I'm mostly struggling to understand how `handle_store` could be re-written to support this. The current implementation requires that data be encoded ahead of time. This is fine for small strings, but would not be suitable for other data types (e.g.: imagine copying an image and having to encode it, potentially into multiple mime types, regardless of whether is it ever pasted in any of those types).

Ideally, `handle_store` would take a `Fn` which returns the data in the requested mime type. It's not clear to me if it would be best for the `Fn` to take the file descriptor as parameter, or if it should be expected to return the data as a `&[u8]` . I appreciate some insight on this. I admit that I'm not entirely certain how to design an API that entirely makes sense. The main issue would be the lifetime of this `Fn` due to the fact that it most definitely needs to have references to application code.

The simplest option would be for the `Fn` to have no special lifetime requirements. The application developer could then have a channel inside of it to their application, or an `Arc` or whatever it suitable for their use case. Somehow I feel that the usage of the API could be better, although maybe I'm letting perfecting get in the way of good here.

OTOH, reading from the clipboard would not be as problematic. The current `load` function could be extended to take a mime_type parameter and read that one specifically. The only risk I see here is that reads are blocking which might be an issue with clients that pass a non-blocking fd or simply write very slowly.

I think the best place for me to start is extending the `load` functions to allow reading non-text, and then use the added experience to work on the `store` functions.

Any feedback or guidance on all this? I don't want to start hacking on something where you see some obvious issue or maybe have alternative plans.

**Comment by kchibisov** [comment]
I'd mark this as out of scope for this particular crate. The issue with it that it's a hack to get clipboard working for applications like winit, however winit itself should provide a clipboard handling.

When SCTK is beind used, it's better to use its infra for the clipboard instead of this crate.

For clipboard managers, application should use data control, which is out of the scope for this crate.

I guess, we'll just leave with strings.

I could reply on how such API could be done if you want to know in general, but basically you'd need to pass `Fn` when the client picks the mime-type, so the user of the library could run their filter. The data should be stored as `Rc<[u8]>` or maybe some other container like that...

**Comment by WhyNotHugo** [comment]
> The data should be stored as Rc<[u8]> or maybe some other container like that...

This is not a good idea; ideally application code should receive the file descriptor and write into it.

Consider for example the situation of copying an image (or even a video) on an image editor. The editor can encode and stream the data into the file descriptor itself. Having to write it into an `Rc<[u8]>` means writing the entire blob to memory _and then_ coping that into the file descriptor.

I wrote some others ideas on what an API could look like here: https://github.com/iced-rs/iced/discussions/1455#discussion-4443808 That's a discussion for another toolkit, but the general situation is pretty much the same, so everything is applicable.

**Comment by kchibisov** [comment]
I mean it can, but you'd still have platforms without a file descriptors concepts, etc. Surely it'll work on Wayland/X11, but macOS will want you a real thing in the end. You can provide a closure serving data, it's not a big deal or something. It's just out of scope for this crate.

**Comment by WhyNotHugo** [comment]
Yup, a closure might work. Passing to it a per-platform wrapper that implements `Write` might work too. This wrapper can be an `fd` on most platforms, an something that writes into memory for macOS if it needs the data pre-rendered in memory.

> It's just out of scope for this crate.

Sure, sure. Not trying to force this into scope.
