### ISSUE TITLE
[FR] please update to to wayland* 0.30

### ISSUE THREAD

**Issue by werdahias** [Smithay/smithay-clipboard#44]
Hi, the current version of the rust wayland stack is 0.30. Please consider updating this crate so it's on par with the rest. I tried updating it but it results in a lot of unresolved imports.

**Comment by kchibisov** [comment]
I'm not that interested in this crate given that I'll try to move ecosystem away from it and copypasta crate all together to direct handling in winit & client-toolkit.

I know that @wash2 was sort of interested in updating this crate, but that's all I can say.
