### ISSUE TITLE
alacritty warning queue destroyed while proxies still attached

### ISSUE THREAD

**Issue by shanechko** [Smithay/smithay-clipboard#46]
Alacritty prints warning on exit:

warning: queue 0x7fc404000cc0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190081 still attached
  wl_data_offer@4278190080 still attached
  zwp_primary_selection_device_v1@29 still attached
  zwp_primary_selection_device_manager_v1@25 still attached
  wl_data_device@28 still attached
  wl_data_device_manager@27 still attached
  wl_seat@26 still attached
  wl_registry@24 still attached

Thread 3 "smithay-clipboa" hit Breakpoint 1, 0x00007ffff7fb6e20 in wl_event_queue_destroy () from /usr/lib64/libwayland-client.so
(gdb) bt
#0  0x00007ffff7fb6e20 in wl_event_queue_destroy () from /usr/lib64/libwayland-client.so
#1  0x0000555555c842f6 in wayland_client::imp::event_queue::{impl#1}::drop (self=0x7fffe8000c50) at src/native_lib/event_queue.rs:139
#2  0x0000555555c7a877 in core::ptr::drop_in_place<wayland_client::imp::event_queue::EventQueueInner> () at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ptr/mod.rs:497
#3  0x0000555555c7b503 in alloc::rc::{impl#20}::drop<wayland_client::imp::event_queue::EventQueueInner> (self=0x7ffff7536f38) at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/rc.rs:1607
#4  0x0000555555c7ad4b in core::ptr::drop_in_place<alloc::rc::Rc<wayland_client::imp::event_queue::EventQueueInner>> () at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ptr/mod.rs:497
#5  0x0000555555bc1a97 in core::ptr::drop_in_place<wayland_client::event_queue::EventQueue> () at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ptr/mod.rs:497
#6  0x0000555555bcccc0 in smithay_clipboard::worker::worker_impl (display=..., request_rx=..., reply_tx=...) at src/worker/mod.rs:321
#7  0x0000555555bcb6dc in smithay_clipboard::worker::spawn::{closure#0} () at src/worker/mod.rs:44
…

**Comment by kchibisov** [comment]
that's expected as of now, in the context of alacritty it's all innocent.
